spring.application.name=agent
langchain4j.open-ai.chat-model.api-key=
langchain4j.open-ai.chat-model.model-name=gpt-4o-2024-08-06
langchain4j.open-ai.chat-model.log-requests=false
langchain4j.open-ai.chat-model.log-responses=false